# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Arun's homepage"
title_separator          : "-"
name                     : &name "Arun P.U."
description              : &description "welcome to my homepage on the WWW"
url                      : https://puarun.github.io # the base hostname & protocol for your site e.g. "https://[your GitHub username].github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "academicpages/academicpages.github.io"
description              : Bookmark this to keep an eye on my project updates!
theme                    : jekyll-theme-minimal

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : 
  name             : "Arun P.U."
  pronouns         : # example: "she/her"  
  bio              : "AI/ ML Researcher and applications Engineer"
  location         : "Seattle, WA"
  employer         : "Best Buy"
  uri              : # URL
  email            : "none@example.org" 

  # Academic websites
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    : "https://scholar.google.com/citations?user=va3grGAAAAAJ&hl=en&oi=ao"
  impactstory      : # URL
  orcid            : "http://orcid.org/0009-0003-3134-8536"
  semantic         : # URL
  pubmed           : 
  researchgate     : # URL
  scopus           : # URL

  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  github           : "puarun"
  kaggle           : # Username  
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")    

  # Social media
  bluesky          : # Replace this with you Bluesky username
  facebook         : # Username
  flickr           : # Username
  foursquare       : # Username
  goodreads        : # Username
  google_plus      : # Username
  keybase          : # Username
  instagram        : # Username
  lastfm           : # Username
  linkedin         : # Username
  mastodon         : # URL
  medium           : # URL
  pinterest        : # Username
  soundcloud       : # Username
  steam            : # Username
  telegram         : # URL
  tumblr           : # Username
  twitter          : # Username for X / Twitter
  vine             : # Username
  weibo            : # Username
  wikipedia        : # Username
  xing             : # Username
  youtube          : # Username
  zhihu            : # Username

# Publication Category - The following the list of publication categories and their headings
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'
